---
title: "Bike Share Workflow Quarto"
format: html
---

```{r}
library(tidyverse)
library(tidymodels)
library(vroom)
library(glue)
library(glmnet)
```

```{r}
train_data <- vroom("train.csv") |>
  select(-casual, -registered) |>
  mutate(count = log(count))
test_data <- vroom("test.csv")
```

```{r}
my_recipe <- recipe(count ~ ., data=train_data) |>
  step_mutate(weather=ifelse(weather == 4, 3L, weather)) |>
  step_mutate(season = as.factor(season)) |>
  step_time(datetime, features="hour") |>
  step_date(datetime, features="dow") |>
  step_rm(datetime) |>
  step_dummy(all_nominal_predictors()) |>
  step_normalize(all_numeric_predictors())
  
```

```{r}
#prepped_recipe <- prep(my_recipe) # Sets up the preprocessing using myDataSet
#train_data <- bake(prepped_recipe, new_data=train_data)
#str(train_data)
```

```{r}
## Penalized regression model3
preg_model <- linear_reg(penalty=tune(), mixture=tune()) %>% 
  set_engine("glmnet") # Function to fit in R

preg_wf <- workflow() %>%
  add_recipe(my_recipe) %>%
  add_model(preg_model)

grid_of_tuning_params <- grid_regular(penalty(), mixture(), levels = 4)

folds <- vfold_cv(train_data, v = 5, repeats=1)
```

```{r}
CV_results <- preg_wf %>%
  tune_grid(resamples=folds,
  grid=grid_of_tuning_params,
  metrics=metric_set(rmse, mae))

collect_metrics(CV_results) %>% # Gathers metrics into DF8
  filter(.metric=="rmse") %>%
  ggplot(data=., aes(x=penalty, y=mean, color=factor(mixture))) +
  geom_line()

bestTune <- CV_results %>%
  select_best(metric="rmse")
```

```{r}
final_wf <- preg_wf %>%
  finalize_workflow(bestTune) %>%
  fit(data=train_data)

## Predict7
tuned_predictions <- final_wf %>%
  predict(new_data = test_data)
```

```{r}
bestTune[1]
```


```{r}
kaggle_submission <- tuned_predictions %>%
    mutate(.pred=exp(.pred)) %>%
    bind_cols(., test_data) %>% #Bind predictions with test data
    select(datetime, .pred) %>% #Just keep datetime and prediction variables
    rename(count=.pred) %>% #rename pred to count (for submission to Kaggle)
    mutate(count=pmax(0, count)) %>% #pointwise max of (0, prediction)
    mutate(datetime=as.character(format(datetime)))

vroom_write(x=kaggle_submission, file=glue("./Tuned_Linear_Predictions_{glue_collapse(bestTune[1:2], sep = '-')}.csv"), delim=",")
```

