---
title: "Bike Share Workflow Quarto"
format: html
---

```{r}
library(tidyverse)
library(tidymodels)
library(vroom)
library(glue)
library(glmnet)
library(rpart)
library(ranger)
library(bonsai)
library(lightgbm)
```

```{r}
train_data <- vroom("train.csv") |>
  select(-casual, -registered) |>
  mutate(count = log(count))
test_data <- vroom("test.csv")
```

```{r}
my_recipe <- recipe(count ~ ., data=train_data) |>
  step_mutate(weather=ifelse(weather == 4, 3L, weather)) |>
  #step_mutate(season = as.factor(season)) |>
  step_time(datetime, features="hour") |>
  step_date(datetime, features=c("dow", "month")) |>
  step_mutate(datetime_dow_num = as.numeric(datetime_dow)) |>
  step_mutate(hour_sin = sin(2 * pi * datetime_hour / 24), 
              hour_cos = cos(2 * pi * datetime_hour / 24),
              dow_sin = sin(2 * pi * datetime_dow_num / 7),
              dow_cos = cos(2 * pi * datetime_dow_num / 7),
              #doy_sin = sin(2 * pi * datetime_doy / 365),
              #doy_cos = cos(2 * pi * datetime_doy / 365),
              #temp_hour = temp * datetime_hour,
              #weekend_hour = (1 - workingday) * datetime_hour,
              #weather_temp = weather * temp,
              #humidity_temp = humidity * temp,
              #wind_temp = windspeed * (1 / (temp + 1)),
              rush_hour = as.integer(datetime_hour %in% c(7, 8, 9, 17, 18, 19)),
              morning_rush = as.integer(datetime_hour %in% c(7, 8, 9)),
              evening_rush = as.integer(datetime_hour %in% c(17, 18, 19)),
              business_hours = as.integer(datetime_hour >= 9 & datetime_hour < 17)) |>
  step_rm(datetime_dow) |>
  step_rm(datetime_dow_num) |>
  step_rm(datetime) |>
  step_dummy(all_nominal_predictors())
```

```{r}
#prepped_recipe <- prep(my_recipe) # Sets up the preprocessing using myDataSet
#train_data <- bake(prepped_recipe, new_data=train_data)

#vroom_write(x=train_data, file=glue("./Baked_Dataset.csv"), delim=",")

#prepped_recipe <- prep(my_recipe) # Sets up the preprocessing using myDataSet
#test_data <- bake(prepped_recipe, new_data=test_data)

#vroom_write(x=test_data, file=glue("./Baked_Dataset_Test.csv"), delim=",")
```

```{r}
# boost_model <- boost_tree(tree_depth=tune(), trees=tune(), learn_rate=tune()) %>%
#   set_engine("lightgbm") %>% #or "xgboost" but lightgbm is faster
#   set_mode("regression")

boost_model <- boost_tree(
  trees = tune(),           # number of trees
  tree_depth = tune(),      # max depth of trees
  min_n = tune(),           # minimum observations in node
  loss_reduction = tune(),  # minimum loss reduction for split
  sample_size = tune(),     # proportion of data for each tree
  mtry = tune(),            # number of predictors randomly sampled
  learn_rate = tune()       # learning rate (eta)
) |>
  set_engine("xgboost") |>
  set_mode("regression")
```

```{r}
preg_wf <- workflow() %>%
  add_recipe(my_recipe) %>%
  add_model(boost_model)

grid_of_tuning_params <- grid_space_filling(
  trees(), 
  tree_depth(), 
  min_n(), 
  loss_reduction(), 
  sample_prop(),  
  finalize(mtry(), train_data),  
  learn_rate(), 
  size = 30  # Only 30 combinations instead of 78k!
)

folds <- vfold_cv(train_data, v = 5, repeats=1)
```

```{r}
CV_results <- preg_wf %>%
  tune_grid(resamples=folds,
  grid=grid_of_tuning_params,
  metrics=metric_set(rmse, mae))

```

```{r}
bestTune <- CV_results %>%
  select_best(metric="rmse")
```

```{r}
final_wf <- preg_wf %>%
  finalize_workflow(bestTune) %>%
  fit(data=train_data)

## Predict7
tree_predictions <- final_wf %>%
  predict(new_data = test_data)

```

```{r}
## Format the Predictions for Submission to Kaggle
kaggle_submission <- tree_predictions %>%
  mutate(.pred=exp(.pred)) %>%
  bind_cols(., test_data) %>% #Bind predictions with test data
  select(datetime, .pred) %>% #Just keep datetime and prediction variables
  rename(count=.pred) %>% #rename pred to count (for submission to Kaggle)
  mutate(count=pmax(0, count)) %>% #pointwise max of (0, prediction)
  mutate(datetime=as.character(format(datetime)))

vroom_write(x=kaggle_submission, file="./XGBoosted_Predictions_1.csv", delim=",")
```
