---
title: "Bike Share Workflow Quarto"
format: html
---

```{r}
library(tidyverse)
library(tidymodels)
library(vroom)
```

```{r}
train_data <- vroom("train.csv") |>
  select(-casual, -registered) |>
  mutate(count = log(count))
test_data <- vroom("test.csv")
```

```{r}
my_recipe <- recipe(count ~ ., data=train_data) |>
  step_mutate(weather=factor(weather, levels=c(1,2,3,4), labels=c("1", "2", "3", "3"))) |>
  step_time(datetime, features="hour") |>
  step_mutate(season = as.factor(season)) |>
  step_date(datetime, features="dow")
  
```

```{r}
#prepped_recipe <- prep(my_recipe) # Sets up the preprocessing using myDataSet
#train_data <- bake(prepped_recipe, new_data=train_data)
```

```{r}
linear_model <- linear_reg() |>
  set_engine("lm") |>
  set_mode("regression")
```

```{r}
bike_workflow <- workflow() |>
  add_recipe(my_recipe) |>
  add_model(linear_model) |>
  fit(data=train_data)
```

```{r}
linear_predictions <- predict(bike_workflow, new_data = test_data)
```

```{r}
head(linear_predictions, 5)
```

```{r}
## Format the Predictions for Submission to Kaggle
kaggle_submission <- linear_predictions %>%
  bind_cols(., test_data) %>% #Bind predictions with test data
  select(datetime, .pred) %>% #Just keep datetime and prediction variables
  rename(count=.pred) %>% #rename pred to count (for submission to Kaggle)
  mutate(count=pmax(0, count)) %>% #pointwise max of (0, prediction)
  mutate(datetime=as.character(format(datetime)))

vroom_write(x=kaggle_submission, file="./LinearPredsFromWorkflow.csv", delim=",")
```

Just stuff to work off of below \>\>\>

```{r}
my_recipe <- recipe(count ~ ., data=train_data) %>% # Set model formula and dataset
  step_mutate(weather=factor(weather, levels=, labels=)) %>% #Make something a factor
  step_mutate(newVar=var1*var2) %>% #Create a new variable
  step_poly(var, degree=2) %>% #Create polynomial expansion of var
  step_date(timestamp, features="dow") %>% # gets day of week
  step_time(timestamp, features=c("hour", "minute")) %>% #create time variable
  step_dummy(all_nominal_predictors()) %>% #create dummy variables
  step_zv(all_predictors()) %>% #removes zero-variance predictors
  step_corr(all_predictors(), threshold=0.5) %>% # removes > than .5 corr
  step_rm(var) %>% #removes a variables
  step_select(var, -var2) #selects columns
prepped_recipe <- prep(my_recipe) # Sets up the preprocessing using myDataSet
bake(prepped_recipe, new_data=A_Data_Set)
```
