---
title: "Bike Share Workflow Quarto"
format: html
---

```{r}
library(tidyverse)
library(tidymodels)
library(vroom)
library(glue)
library(glmnet)
```

```{r}
train_data <- vroom("train.csv") |>
  select(-casual, -registered) |>
  mutate(count = log(count))
test_data <- vroom("test.csv")
```

```{r}
my_recipe <- recipe(count ~ ., data=train_data) |>
  step_mutate(weather=ifelse(weather == 4, 3L, weather)) |>
  step_mutate(season = as.factor(season)) |>
  step_time(datetime, features="hour") |>
  step_date(datetime, features="dow") |>
  step_rm(datetime) |>
  step_dummy(all_nominal_predictors()) |>
  step_normalize(all_numeric_predictors())
  
```

```{r}
#prepped_recipe <- prep(my_recipe) # Sets up the preprocessing using myDataSet
#train_data <- bake(prepped_recipe, new_data=train_data)
#str(train_data)

#vroom_write(x=train_data, file=glue("./Baked_Dataset.csv"), delim=",")
```

```{r}
#prepped_recipe <- prep(my_recipe) # Sets up the preprocessing using myDataSet
#test_data <- bake(prepped_recipe, new_data=test_data)
#str(test_data)

#vroom_write(x=test_data, file=glue("./Baked_Dataset_Test.csv"), delim=",")
```


```{r}
test_parameters <- list(c(1,0), c(1,1), c(1, 0.5), c(3, 0.5), c(3, 1), c(2, 0), c(0.5, 0))

for (parameters in test_parameters) {

  penalized_regression_model <- linear_reg(penalty=parameters[1], mixture=parameters[2]) %>%
    set_engine("glmnet")
  
  bike_workflow <- workflow() |>
    add_recipe(my_recipe) |>
    add_model(penalized_regression_model) |>
    fit(data=train_data)
  
  linear_predictions <- predict(bike_workflow, new_data = test_data)
  
  ## Format the Predictions for Submission to Kaggle
  kaggle_submission <- linear_predictions %>%
    mutate(.pred=exp(.pred)) %>%
    bind_cols(., test_data) %>% #Bind predictions with test data
    select(datetime, .pred) %>% #Just keep datetime and prediction variables
    rename(count=.pred) %>% #rename pred to count (for submission to Kaggle)
    mutate(count=pmax(0, count)) %>% #pointwise max of (0, prediction)
    mutate(datetime=as.character(format(datetime)))
  
  vroom_write(x=kaggle_submission, file=glue("./Penalized_Linear_Predictions_{glue_collapse(parameters, sep = '-')}.csv"), delim=",")
}
```