---
title: "Bike Share Quarto"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(tidymodels)
```

```{r}
train_data <- vroom("train.csv") |>
  select(-casual, -registered)
test_data <- vroom("test.csv")
```

```{r}
## Setup and Fit the Linear Regression Model
my_linear_model <- linear_reg() %>% #Type of model
  set_engine("lm") %>% # Engine = What R function to use
  set_mode("regression") %>% # Regression just means quantitative response
  fit(formula=count ~ .-datetime, data=train_data)

## Generate Predictions Using Linear Model
bike_predictions <- predict(my_linear_model, new_data=test_data) # Use fit to predict
bike_predictions ## Look at the output
```

```{r}
## Format the Predictions for Submission to Kaggle
kaggle_submission <- bike_predictions %>%
  bind_cols(., test_data) %>% #Bind predictions with test data
  select(datetime, .pred) %>% #Just keep datetime and prediction variables
  rename(count=.pred) %>% #rename pred to count (for submission to Kaggle)
  mutate(count=pmax(0, count)) %>% #pointwise max of (0, prediction)
  mutate(datetime=as.character(format(datetime))) 

## Write out the file
vroom_write(x=kaggle_submission, file="./LinearPreds.csv", delim=",")
```
